import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * The docs sidebar is autogenerated from the folder structure under docs/.
 * Each folder carries a _category_.json describing its label and position,
 * so adding a page is just dropping a Markdown file in the right folder.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
